- .gitignore
This PR adds the python gitignore based on this: https://www.gitignore.io/api/python
> improving .gitignore

- autoxtrabackup.py
- setup.py
Read more here:
https://github.com/ShahriyarR/MySQL-AutoXtraBackup/pull/32
> added basic git version integration

- autoxtrabackup.py
- setup.py
Reverts ShahriyarR/MySQL-AutoXtraBackup#35
> Revert "added basic git version integration"

- general_conf/check_env.py
- master_backup_script/backuper.py
> Preliminary fix for issue #38

- backup_prepare/prepare.py
- general_conf/bck.conf
- general_conf/generalops.py
- master_backup_script/backuper.py
> Bugfix issue41

- general_conf/check_env.py
- master_backup_script/backuper.py
> Bugfix issue44

- general_conf/check_env.py
> Preliminary fix for issue #45

- autoxtrabackup.py
> Bugfix issue53

- README.md
- autoxtrabackup.py
- partial_recovery/partial.py
> Bugfix issue55

- README.md
> Bugfix issue61

- autoxtrabackup.py
- setup.py
> Changing version numbers for releasing new version

- docs/config_file.rst
> fix grammar

- backup_prepare/prepare.py
> prepare.py FIX for bug #70

- autoxtrabackup.py
- backup_prepare/prepare.py
- master_backup_script/backuper.py
Superficial refactor to some lines to improve readability. Also remove some redundant conditionals like,
```
def foo(x): #
if x>0:
return x
else:
return 0
```
Above snippet could be rewritten as
```
def foo(x): #
if x>0:
return x
return 0
```
or, 
```
def foo(x):
return x if x>0 else 0
```
to save some bytes.
> Improvements

- master_backup_script/backuper.py
> Preliminary fix for issue #72

- docs/advance_features.rst
- general_conf/bck.conf
- general_conf/generalops.py
- master_backup_script/backuper.py
> Bugfix issue48

- test/test_partialRecovery.py
> Bugfix issue76

- autoxtrabackup.py
- backup_prepare/prepare.py
- general_conf/bck.conf
- general_conf/generalops.py
- master_backup_script/backuper.py
> Bugfix issue77

- backup_prepare/prepare.py
- master_backup_script/backuper.py
> Preliminary fix for issue #79

- backup_prepare/prepare.py
- general_conf/bck.conf
- general_conf/generalops.py
- master_backup_script/backuper.py
> Preliminary fix for issue #87

- backup_prepare/prepare.py
- general_conf/bck.conf
- general_conf/generalops.py
> Preliminary fix for issue #89

- autoxtrabackup.py
- general_conf/bck.conf
- general_conf/generalops.py
- prepare_env_test_mode/clone_build_start_server.py
- prepare_env_test_mode/run_benchmark.py
- prepare_env_test_mode/test_check_env.py
- setup.py
- test/conftest.py
- test/test_prepare_env_test.py
- test/test_run_benchmark.py
Fixed #99 
Please see issue for comments.
> Bugfix issue99

- __init__.py
- autoxtrabackup.py
- prepare_env_test_mode/clone_build_start_server.py
- prepare_env_test_mode/run_benchmark.py
- prepare_env_test_mode/runner_test_mode.py
- setup.py
- test/test_prepare_env_test.py
> Bugfix issue101

- general_conf/bck.conf
- general_conf/check_env.py
- general_conf/generalops.py
- master_backup_script/backuper.py
- prepare_env_test_mode/config_generator.py
- prepare_env_test_mode/runner_test_mode.py
- prepare_env_test_mode/take_backup.py
- test/conftest.py
- test/test_take_backup.py
> Bugfix issue103

- prepare_env_test_mode/prepare_backup.py
- prepare_env_test_mode/runner_test_mode.py
- test/conftest.py
- test/test_prepare_backup.py
> Bugfix issue107

- general_conf/bck.conf
- general_conf/generalops.py
- prepare_env_test_mode/clone_build_start_server.py
- prepare_env_test_mode/config_generator.py
- prepare_env_test_mode/runner_test_mode.py
- prepare_env_test_mode/test_check_env.py
> Preliminary fix for issue #109

- general_conf/bck.conf
- general_conf/generalops.py
- prepare_env_test_mode/clone_build_start_server.py
- prepare_env_test_mode/config_generator.py
- test/test_clone_build_start_server.py
> Bugfix issue111

- general_conf/bck.conf
- prepare_env_test_mode/config_generator.py
- prepare_env_test_mode/run_benchmark.py
- test/test_config_generator.py
> Bugfix issue113

- .gitignore
- Vagrantfile
- __init__.py
- prepare_env_test_mode/clone_build_start_server.py
- setup.py
> Bugfix issue115

- prepare_env_test_mode/run_benchmark.py
- test/test_run_benchmark.py
> Bugfix issue122

- prepare_env_test_mode/clone_build_start_server.py
- prepare_env_test_mode/config_generator.py
- prepare_env_test_mode/take_backup.py
- test/conftest.py
- test/test_take_backup.py
> Bugfix issue120

- prepare_env_test_mode/prepare_backup.py
- test/conftest.py
- test/test_prepare_backup.py
> Bugfix issue125

- general_conf/bck.conf
- general_conf/generalops.py
- prepare_env_test_mode/clone_build_start_server.py
- prepare_env_test_mode/config_generator.py
- prepare_env_test_mode/runner_test_mode.py
- test/conftest.py
- test/prepare_env.bats
- test/test_config_generator.py
- test/test_option_combinations.py
- test/test_runner_test_mode.py
> Bugfix issue119

- general_conf/check_env.py
- master_backup_script/backuper.py
- prepare_env_test_mode/runner_test_mode.py
- prepare_env_test_mode/take_backup.py
> Bugfix issue128

- backup_prepare/prepare.py
- prepare_env_test_mode/prepare_backup.py
- prepare_env_test_mode/runner_test_mode.py
> Bugfix issue130

- backup_prepare/prepare.py
- prepare_env_test_mode/runner_test_mode.py
> Preliminary fix for issue #132

- partial_recovery/partial.py
> Preliminary fix for issue #116

- autoxtrabackup.py
> Preliminary fix for issue #135

- prepare_env_test_mode/run_benchmark.py
- prepare_env_test_mode/runner_test_mode.py
- prepare_env_test_mode/take_backup.py
> Bugfix issue138

- test/test_run_benchmark.py
> Added new test and fixed previous one for issue #140

- docs/advance_features.rst
- docs/basic_features.rst
- docs/basic_overview.rst
- docs/index.rst
- docs/intro.rst
- docs/test_mode.rst
> Bugfix issue137

- general_conf/bck.conf
- master_backup_script/backuper.py
- prepare_env_test_mode/config_generator.py
- prepare_env_test_mode/prepare_backup.py
- prepare_env_test_mode/run_benchmark.py
- prepare_env_test_mode/runner_test_mode.py
- prepare_env_test_mode/take_backup.py
- test/test_runner_test_mode.py
> Bugfix issue144

- autoxtrabackup.py
> Bugfix issue147

- backup_prepare/prepare.py
- general_conf/check_env.py
- master_backup_script/backuper.py
- partial_recovery/partial.py
> Bugfix issue150

- prepare_env_test_mode/config_generator.py
> Preliminary fix for issue #152

- general_conf/bck.conf
- prepare_env_test_mode/config_generator.py
> Preliminary fix for issue #151

- prepare_env_test_mode/runner_test_mode.py
> Bugfix issue157

- backup_prepare/prepare.py
> Bugfix issue158

- autoxtrabackup.py
> Bugfix issue162

- autoxtrabackup.py
- setup.py
> Bugfix issue166

- backup_dir/README.txt
- backup_prepare/prepare.py
- general_conf/check_env.py
- master_backup_script/backuper.py
- partial_recovery/partial.py
> Bugfix issue168

- prepare_env_test_mode/config_generator.py
> preliminary fix for issue #170

- autoxtrabackup.py
- master_backup_script/backuper.py
- test/conftest.py
- test/test_backup.py
- test/test_test_prepare_backup.py
- test/test_test_take_backup.py
> Bugfix issue163

- autoxtrabackup.py
- master_backup_script/backuper.py
- test/test_backup.py
> Bugfix issue164

- prepare_env_test_mode/config_generator.py
- prepare_env_test_mode/run_benchmark.py
- prepare_env_test_mode/runner_test_mode.py
- prepare_env_test_mode/take_backup.py
> Bugfix issue171

- prepare_env_test_mode/run_benchmark.py
- prepare_env_test_mode/take_backup.py
> Bugfix issue172

- autoxtrabackup.py
- backup_prepare/prepare.py
> Bugfix issue176

- prepare_env_test_mode/config_generator.py
> Preliminary fix for issue #182

- prepare_env_test_mode/config_generator.py
- test/test_config_generator.py
> Bugfix issue185

- docs/advance_features.rst
- docs/backup_tags.rst
- docs/basic_overview.rst
> Preliminary fix for issue #192

- prepare_env_test_mode/config_generator.py
- prepare_env_test_mode/take_backup.py
> Bugfix issue195

- general_conf/check_env.py
- prepare_env_test_mode/run_benchmark.py
- prepare_env_test_mode/runner_test_mode.py
- prepare_env_test_mode/take_backup.py
> Bugfix issue196

- backup_prepare/prepare.py
> Bugfix issue199

- autoxtrabackup.py
- general_conf/bck.conf
- prepare_env_test_mode/clone_build_start_server.py
- prepare_env_test_mode/config_generator.py
- prepare_env_test_mode/run_benchmark.py
- prepare_env_test_mode/runner_test_mode.py
- prepare_env_test_mode/take_backup.py
- test/test_clone_build_start_server.py
> Bugfix issue197

- backup_prepare/prepare.py
- general_conf/bck.conf
- master_backup_script/backuper.py
> Bugfix issue194

- prepare_env_test_mode/config_generator.py
> Preliminary fix for issue #204

- prepare_env_test_mode/take_backup.py
> Bugfix issue206

- prepare_env_test_mode/take_backup.py
> Bugfix issue205

- prepare_env_test_mode/build_2.3_pxb.sh
- prepare_env_test_mode/build_2.4_pxb.sh
- prepare_env_test_mode/clone_build_start_server.py
- prepare_env_test_mode/start_dynamic.sh
- test/prepare_env.bats
- test/test_clone_build_start_server.py
> Bugfix issue213

- master_backup_script/backuper.py
- prepare_env_test_mode/clone_build_start_server.py
> Bugfix issue210

- Vagrantfile
- setup.py
> Bugfix issue217

- prepare_env_test_mode/runner_test_mode.py
- prepare_env_test_mode/take_backup.py
> Bugfix issue219

- prepare_env_test_mode/clone_build_start_server.py
> Preliminary fix for issue #225

- prepare_env_test_mode/run_benchmark.py
- prepare_env_test_mode/take_backup.py
> Preliminary fix for issue #229

- prepare_env_test_mode/runner_test_mode.py
- prepare_env_test_mode/take_backup.py
> Bugfix issue222

- test/README.md
- test/test_build_pxb.bats
- test/test_build_server.bats
- test/test_clone_percona_qa.bats
- test/test_clone_ps_server_from_conf.bats
- test/test_clone_pxb.bats
- test/test_extract_xb_archive.bats
- test/test_generate_config_files.bats
- test/test_prepare_start_dynamic.bats
- test/test_prepare_startup.bats
- test/test_start_server.bats
> Preliminary fix for issue #233

- master_backup_script/backuper.py
> Fixed #228

- master_backup_script/backuper.py
> Preliminary fix for issue #223

- docs/backup_tags.rst
- docs/basic_features.rst
- docs/config_file.rst
- docs/test_mode.rst
- test/README.md
> Preliminary fix for issue #215

- autoxtrabackup.py
- general_conf/bck.conf
- general_conf/generalops.py
> Bugfix issue240

- general_conf/bck.conf
- general_conf/generalops.py
- master_backup_script/backuper.py
- prepare_env_test_mode/config_generator.py
> Bugfix issue246

- master_backup_script/backuper.py
- prepare_env_test_mode/take_backup.py
> Bugfix issue245

- prepare_env_test_mode/config_generator.py
- test/prepare_env.bats
- test/test_rename_basedirs.bats
> Bugfix issue250

- master_backup_script/backuper.py
> Bugfix issue260

- prepare_env_test_mode/config_generator.py
- prepare_env_test_mode/take_backup.py
Fixed #264
Added --innodb_encrypt_tables=ON to default mysqld options list.
Changed some tests not to fail with this new configuration change.
> Bugfix issue264

- prepare_env_test_mode/config_generator.py
> Bugfix issue262

- prepare_env_test_mode/config_generator.py
> Preliminary fix for issue #263

- prepare_env_test_mode/call_innodb_online_alter_encryption_alters.sh
- prepare_env_test_mode/call_innodb_online_alter_encryption_sql.sh
- prepare_env_test_mode/innodb_online_alter_encryption.sql
- prepare_env_test_mode/innodb_online_alter_encryption_alters.sql
- prepare_env_test_mode/take_backup.py
Adopted the MTR test for PXB test framework it is ready to be merged to release_v1.5.2 branch
> Bugfix issue271

- autoxtrabackup.py
- prepare_env_test_mode/call_innodb_online_alter_encryption_alters.sh
- prepare_env_test_mode/runner_test_mode.py
- prepare_env_test_mode/take_backup.py
- setup.py
> Bugfix issue275

- autoxtrabackup.py
- general_conf/bck.conf
- general_conf/generalops.py
- master_backup_script/backuper.py
- prepare_env_test_mode/call_create_index_temp.sh
- prepare_env_test_mode/call_ddl_test.sh
- prepare_env_test_mode/call_innodb_online_alter_encryption_alters.sh
- prepare_env_test_mode/call_innodb_online_alter_encryption_sql.sh
- prepare_env_test_mode/call_temp_table_test.sh
- prepare_env_test_mode/config_generator.py
- prepare_env_test_mode/create_index_temp.sh
- prepare_env_test_mode/ddl_test.sh
- prepare_env_test_mode/innodb_online_alter_encryption.sql
- prepare_env_test_mode/innodb_online_alter_encryption_alters.sql
- prepare_env_test_mode/runner_test_mode.py
- prepare_env_test_mode/take_backup.py
- prepare_env_test_mode/temp_table_test.sh
- setup.py
- test/prepare_env.bats
- test/test_rename_basedirs.bats
Releasing new version of autoxtrabackup v1.5.2
> Release v1.5.2

- prepare_env_test_mode/call_create_index_temp.sh
- prepare_env_test_mode/call_ddl_test.sh
- prepare_env_test_mode/call_temp_table_test.sh
> Preliminary fix for issue #278

- master_backup_script/backuper.py
About issue #284 
I've implemented the availability test you suggested: If not found use normal 'tar.gz' and log a warning. And when available use pigz.
> Optional multi-core archiving (pigz)

- setup.py
> Change setup path of bck.conf file

- autoxtrabackup.py
- general_conf/path_config.py
> Changed the log file path from /var/log to ~/.autoxtrabackup

- general_conf/__init__.py
> Removing things inside __init__.py

- prepare_env_test_mode/temp_table_test.sh
> Changing encryption

- autoxtrabackup.py
- backup_prepare/prepare.py
- docs/basic_overview.rst
- docs/config_file.rst
- docs/installation.rst
- docs/option_reference.rst
- docs/test_mode.rst
- general_conf/__init__.py
- general_conf/autoxtrabackup.cnf
- general_conf/check_env.py
- general_conf/generalops.py
- general_conf/path_config.py
- master_backup_script/backuper.py
- partial_recovery/partial.py
- prepare_env_test_mode/call_create_index_temp.sh
- prepare_env_test_mode/call_ddl_test.sh
- prepare_env_test_mode/call_temp_table_test.sh
- prepare_env_test_mode/clone_build_start_server.py
- prepare_env_test_mode/config_generator.py
- prepare_env_test_mode/prepare_backup.py
- prepare_env_test_mode/run_benchmark.py
- prepare_env_test_mode/runner_test_mode.py
- prepare_env_test_mode/take_backup.py
- prepare_env_test_mode/temp_table_test.sh
- prepare_env_test_mode/test_check_env.py
- requirements.txt
- setup.py
Merging changes for version 1.5.3.
Will be merged after final review.
> Release v1.5.3

- master_backup_script/backuper.py
> Fixing indentation problem for issue #318

- general_conf/generalops.py
- general_conf/generate_default_conf.py
- setup.py
> Changed default config file structure it is generating during setup

- docs/config_file.rst
> Fixed #333

- master_backup_script/backuper.py
update pigz check so it will return exitcode 0 for ProcessRunner. update 2 incorrect calls to ProcessRunner().
Fixes #356
> Update pigz check

- docs/installation.rst
Small improvement for quicker installation
> docs: Improve installation  commands

- process_runner/process_runner.py
> fix #382. Will return error.

- backup_backup/backuper.py
- backup_prepare/prepare.py
- general_conf/generalops.py
- general_conf/generate_default_conf.py
- process_runner/process_runner.py
- utils/helpers.py
- utils/mysql_cli.py
This branch should provide necessary code changes in order to get more robust core project.
> Code Refactoring - cleaning actions (extra)

- backup_backup/backuper.py
- backup_prepare/copy_back.py
- backup_prepare/prepare.py
- backup_prepare/prepare_builder.py
- general_conf/generalops.py
- process_runner/errors.py
> It seems to be the Prepare now has single responsibility

- test/Dockerfile
> few changes to Dockerfile

- autoxtrabackup.py
- backup_backup/backup_builder.py
- backup_backup/backuper.py
- backup_prepare/prepare.py
- docker-compose-test.yaml
- general_conf/check_env.py
- general_conf/generalops.py
- utils/helpers.py
- utils/mysql_cli.py
> doing code refactoring for autoxtrabackup.py

- Dockerfile
- Pipfile
- Pipfile.lock
- api/main.py
- autoxtrabackup.py
- docker-compose-test.yaml
- docker-compose.yaml
- requirements.txt
- test/Dockerfile
- test/requirements.txt
> first draft commit for starting to implement api

- api/main.py
- backup_prepare/prepare.py
* First return proper status codes with JSONResponse
> Prepare backup api changes

- Dockerfile
- api/controller/controller.py
- backup_backup/backuper.py
- utils/helpers.py
* Added /delete for removing all backups
* Added checker function if the backup is already prepared or not for full backup - need to add the same thing for incremental as well.
> Added extra API endpoints

- HISTORY.md
- changes/442-shahriyarr.md
- changes/README.md
- changes/make_history.py
> Added changes handler for each release
